### ISSUE TITLE
Slides no repositório

### ISSUE THREAD

**Issue by gildasio** [devnaestrada/dne-meetup#1]
Opa! Gostaria de sugerir colocar os slides das palestras no próprio repositório. Isso pode ser bom para caso a pessoa queira dar um `git clone` e baixar tudo ou até mesmo para centralizar. Sugiro o seguinte:

```
dne-meetup/
    README.md
    01/
        README.md
        titulo_da_palestra_01.pdf (ou)
        titulo_da_palestra_02/
            img/
            css/
            index.html
```

O que acha?

**Comment by femontanha** [comment]
fala @gjuniioor beleza cara?
Acreditamos ser melhor separar porque isso não tem nada a ver com o repositório do nosso site.
Estamos querendo mudar muita coisa e acho que isso não vai entrar!

Valeu
